##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## cmd
##

GENERATOR	=	generator/

all:
		make -C $(GENERATOR)

clean:
		make -C $(GENERATOR) clean

fclean:		clean
		make -C $(GENERATOR) fclean

re:		fclean all

.PHONY:		all clean fclean re
